/* Hades I — Infernal Arms, Boons, Duo Boons, Keepsakes, Mirror, Hammers
   Sources: hades.fandom.com (Infernal Arms / Boons / Duo Boons / Keepsakes / Mirror of Night / Daedalus Hammer) */

const GODS = {
  zeus: { id: "zeus", name: "Zeus", nameZh: "宙斯", color: "#f0c94d", curse: "Jolted", curseZh: "心驚膽戰" },
  poseidon: { id: "poseidon", name: "Poseidon", nameZh: "波塞冬", color: "#3d9bff", curse: "Rupture", curseZh: "斬斷" },
  athena: { id: "athena", name: "Athena", nameZh: "雅典娜", color: "#e6d5a8", curse: "Exposed", curseZh: "暴露" },
  aphrodite: { id: "aphrodite", name: "Aphrodite", nameZh: "阿弗洛狄忒", color: "#ff6ba8", curse: "Weak", curseZh: "虛弱" },
  artemis: { id: "artemis", name: "Artemis", nameZh: "阿爾忒彌斯", color: "#5fd68a", curse: "Critical", curseZh: "暴擊" },
  ares: { id: "ares", name: "Ares", nameZh: "阿瑞斯", color: "#d62839", curse: "Doom", curseZh: "厄運" },
  dionysus: { id: "dionysus", name: "Dionysus", nameZh: "迪奧尼索斯", color: "#b56bff", curse: "Hangover", curseZh: "醉酒" },
  demeter: { id: "demeter", name: "Demeter", nameZh: "得墨忒爾", color: "#8ec8e8", curse: "Chill", curseZh: "冰凍" },
  hermes: { id: "hermes", name: "Hermes", nameZh: "赫爾墨斯", color: "#f5a623", curse: null, curseZh: null },
};

const SLOTS = [
  { id: "attack", name: "Attack", nameZh: "攻擊", suffix: "Strike" },
  { id: "special", name: "Special", nameZh: "特殊", suffix: "Flourish" },
  { id: "cast", name: "Cast", nameZh: "投彈", suffix: "Shot" },
  { id: "dash", name: "Dash", nameZh: "衝刺", suffix: "Dash" },
  { id: "call", name: "Call", nameZh: "求援", suffix: "Aid" },
  { id: "extra", name: "Other", nameZh: "其他", suffix: "" },
  { id: "legendary", name: "Legendary", nameZh: "傳奇", suffix: "" },
];

const BEOWULF_CAST = {
  "crush-shot": { name: "Passion Flare", nameZh: "傾心爆破" },
  "electric-shot": { name: "Thunder Flare", nameZh: "雷霆爆破" },
  "flood-shot": { name: "Flood Flare", nameZh: "洪水爆破" },
  "phalanx-shot": { name: "Phalanx Flare", nameZh: "殺陣爆破" },
  "true-shot": { name: "Hunter's Flare", nameZh: "獵人爆破" },
  "slicing-shot": { name: "Slicing Flare", nameZh: "旋刀爆破" },
  "trippy-shot": { name: "Trippy Flare", nameZh: "致幻爆破" },
  "crystal-beam": { name: "Icy Flare", nameZh: "水晶爆破" },
};

const BOONS = [
  /* ——— Zeus ——— */
  { id: "lightning-strike", god: "zeus", slot: "attack", name: "Lightning Strike", nameZh: "閃電攻擊", effectZh: "攻擊會發出連鎖閃電。" },
  { id: "thunder-flourish", god: "zeus", slot: "special", name: "Thunder Flourish", nameZh: "雷霆亂舞", effectZh: "特殊攻擊使閃電劈向附近敵人。" },
  { id: "electric-shot", god: "zeus", slot: "cast", name: "Electric Shot", nameZh: "雷霆射擊", effectZh: "投彈化為在敵人間彈跳的連鎖閃電。" },
  { id: "thunder-dash", god: "zeus", slot: "dash", name: "Thunder Dash", nameZh: "雷霆衝刺", effectZh: "衝刺時閃電劈向附近敵人。" },
  { id: "zeus-aid", god: "zeus", slot: "call", name: "Zeus' Aid", nameZh: "宙斯之援", effectZh: "求援期間反覆以閃電劈擊附近敵人。" },
  { id: "heavens-vengeance", god: "zeus", slot: "extra", name: "Heaven's Vengeance", nameZh: "雷神懲擊", effectZh: "受傷後，攻擊你的敵人會被閃電擊中。", tags: ["revenge"] },
  { id: "lightning-reflexes", god: "zeus", slot: "extra", name: "Lightning Reflexes", nameZh: "電光石火", effectZh: "在即將被擊中前衝刺，閃電會劈向附近敵人。" },
  { id: "storm-lightning", god: "zeus", slot: "extra", name: "Storm Lightning", nameZh: "風暴閃電", effectZh: "連鎖閃電可彈跳更多次。" },
  { id: "high-voltage", god: "zeus", slot: "extra", name: "High Voltage", nameZh: "高壓雷擊", effectZh: "落雷範圍更大。" },
  { id: "double-strike", god: "zeus", slot: "extra", name: "Double Strike", nameZh: "雙重雷擊", effectZh: "落雷有機率再劈一次。" },
  { id: "static-discharge", god: "zeus", slot: "extra", name: "Static Discharge", nameZh: "靜電釋放", effectZh: "閃電效果會使敵人心驚膽戰（Jolted）。" },
  { id: "clouded-judgement", god: "zeus", slot: "extra", name: "Clouded Judgement", nameZh: "大發雷霆", effectZh: "造成或受到傷害時，神力槽充能更快。" },
  { id: "billowing-strength", god: "zeus", slot: "extra", name: "Billowing Strength", nameZh: "無邊神力", effectZh: "使用求援後短暫提高傷害。" },
  { id: "splitting-bolt", god: "zeus", slot: "legendary", name: "Splitting Bolt", nameZh: "閃電裂變", effectZh: "所有閃電效果額外產生一次爆發。", prereq: { type: "OneOf", ids: ["storm-lightning", "high-voltage", "double-strike"] } },

  /* ——— Poseidon ——— */
  { id: "tempest-strike", god: "poseidon", slot: "attack", name: "Tempest Strike", nameZh: "暴風攻擊", effectZh: "攻擊傷害提高並擊退敵人。" },
  { id: "tempest-flourish", god: "poseidon", slot: "special", name: "Tempest Flourish", nameZh: "暴風亂舞", effectZh: "特殊攻擊傷害提高並擊退敵人。" },
  { id: "flood-shot", god: "poseidon", slot: "cast", name: "Flood Shot", nameZh: "洪水射擊", effectZh: "投彈對範圍造成傷害並擊退。" },
  { id: "tidal-dash", god: "poseidon", slot: "dash", name: "Tidal Dash", nameZh: "海潮衝刺", effectZh: "衝刺對範圍造成傷害並擊退。" },
  { id: "poseidon-aid", god: "poseidon", slot: "call", name: "Poseidon's Aid", nameZh: "波塞冬之援", effectZh: "求援期間無敵衝撞敵人。" },
  { id: "typhoons-fury", god: "poseidon", slot: "extra", name: "Typhoon's Fury", nameZh: "颶風怒吼", effectZh: "將敵人撞向障礙時造成更多傷害。" },
  { id: "hydraulic-might", god: "poseidon", slot: "extra", name: "Hydraulic Might", nameZh: "汪洋之力", effectZh: "遭遇戰開始數秒內，攻擊與特殊更強。" },
  { id: "oceans-bounty", god: "poseidon", slot: "extra", name: "Ocean's Bounty", nameZh: "海洋恩賜", effectZh: "寶石、黑暗、錢幣房間獎勵更豐厚。" },
  { id: "sunken-treasure", god: "poseidon", slot: "extra", name: "Sunken Treasure", nameZh: "海底寶藏", effectZh: "立即獲得寶石、黑暗、錢幣與生命。" },
  { id: "razor-shoals", god: "poseidon", slot: "extra", name: "Razor Shoals", nameZh: "浪如刀割", effectZh: "擊退效果同時造成斬斷（Rupture）。" },
  { id: "boiling-point", god: "poseidon", slot: "extra", name: "Boiling Point", nameZh: "海水沸騰", effectZh: "受傷時神力槽充能更快。" },
  { id: "breaking-wave", god: "poseidon", slot: "extra", name: "Breaking Wave", nameZh: "怒浪滔天", effectZh: "將敵人撞向牆壁或角落時產生水爆。" },
  { id: "wave-pounding", god: "poseidon", slot: "extra", name: "Wave Pounding", nameZh: "驚濤拍浪", effectZh: "擊退類祝福對首領造成額外傷害。" },
  { id: "rip-current", god: "poseidon", slot: "extra", name: "Rip Current", nameZh: "海底激流", effectZh: "求援會拉近敵人且持續更久。" },
  { id: "second-wave", god: "poseidon", slot: "legendary", name: "Second Wave", nameZh: "滔滔不絕", effectZh: "擊退效果會再推一次。", prereq: { type: "OneFromEachSet", sets: [["breaking-wave", "typhoons-fury"], ["tempest-strike", "tempest-flourish", "flood-shot", "tidal-dash", "poseidon-aid"]] } },
  { id: "huge-catch", god: "poseidon", slot: "legendary", name: "Huge Catch", nameZh: "漁獲豐收", effectZh: "更高機率在房間找到釣魚點，並取消「距上次釣魚點需隔幾間房」的限制。", prereq: { type: "TwoOf", ids: ["oceans-bounty", "sunken-treasure"], keepsakes: ["conch-shell"] } },

  /* ——— Athena ——— */
  { id: "divine-strike", god: "athena", slot: "attack", name: "Divine Strike", nameZh: "神聖攻擊", effectZh: "攻擊更強，並可反彈（Deflect）。" },
  { id: "divine-flourish", god: "athena", slot: "special", name: "Divine Flourish", nameZh: "神聖亂舞", effectZh: "特殊攻擊更強，並可反彈。" },
  { id: "phalanx-shot", god: "athena", slot: "cast", name: "Phalanx Shot", nameZh: "殺陣射擊", effectZh: "投彈對小範圍造成傷害，並可反彈。" },
  { id: "divine-dash", god: "athena", slot: "dash", name: "Divine Dash", nameZh: "神聖衝刺", effectZh: "衝刺造成傷害並可反彈。幾乎萬用。" },
  { id: "athena-aid", god: "athena", slot: "call", name: "Athena's Aid", nameZh: "雅典娜之援", effectZh: "短暫無敵並反彈所有攻擊。" },
  { id: "holy-shield", god: "athena", slot: "extra", name: "Holy Shield", nameZh: "神聖盾衛", effectZh: "受傷後對附近敵人造成傷害並短暫反彈。", tags: ["revenge"] },
  { id: "bronze-skin", god: "athena", slot: "extra", name: "Bronze Skin", nameZh: "銅牆鐵壁", effectZh: "減少來自敵人攻擊的傷害。" },
  { id: "sure-footing", god: "athena", slot: "extra", name: "Sure Footing", nameZh: "沉穩步伐", effectZh: "減少陷阱傷害。" },
  { id: "proud-bearing", god: "athena", slot: "extra", name: "Proud Bearing", nameZh: "氣宇軒昂", effectZh: "每場遭遇開始時神力槽已有部分充能。" },
  { id: "blinding-flash", god: "athena", slot: "extra", name: "Blinding Flash", nameZh: "炫目之光", effectZh: "可反彈的技能也會使敵人暴露（Exposed）。" },
  { id: "brilliant-riposte", god: "athena", slot: "extra", name: "Brilliant Riposte", nameZh: "精彩還擊", effectZh: "反彈的攻擊造成更多傷害。" },
  { id: "deathless-stand", god: "athena", slot: "extra", name: "Deathless Stand", nameZh: "屹立不倒", effectZh: "死亡反抗的無敵更久，並立即補一層。" },
  { id: "last-stand", god: "athena", slot: "extra", name: "Last Stand", nameZh: "背水一戰", effectZh: "死亡反抗回復更多生命，並立即補一層。" },
  { id: "divine-protection", god: "athena", slot: "legendary", name: "Divine Protection", nameZh: "神聖保護", effectZh: "擁有可抵銷一次傷害的屏障。", prereq: { type: "OneOf", ids: ["brilliant-riposte"] } },

  /* ——— Aphrodite ——— */
  { id: "heartbreak-strike", god: "aphrodite", slot: "attack", name: "Heartbreak Strike", nameZh: "心碎攻擊", effectZh: "攻擊傷害提高並施加虛弱（Weak）。" },
  { id: "heartbreak-flourish", god: "aphrodite", slot: "special", name: "Heartbreak Flourish", nameZh: "心碎亂舞", effectZh: "特殊攻擊傷害提高並施加虛弱。" },
  { id: "crush-shot", god: "aphrodite", slot: "cast", name: "Crush Shot", nameZh: "傾心一箭", effectZh: "投彈化為短距廣角爆破並施加虛弱。" },
  { id: "passion-dash", god: "aphrodite", slot: "dash", name: "Passion Dash", nameZh: "激情衝刺", effectZh: "衝刺落點造成傷害並施加虛弱。" },
  { id: "aphrodite-aid", god: "aphrodite", slot: "call", name: "Aphrodite's Aid", nameZh: "阿弗洛狄忒之援", effectZh: "發射追蹤彈並施加魅惑（Charm）。" },
  { id: "dying-lament", god: "aphrodite", slot: "extra", name: "Dying Lament", nameZh: "奪命輓歌", effectZh: "敵人死亡時對附近造成傷害並施加虛弱。" },
  { id: "wave-of-despair", god: "aphrodite", slot: "extra", name: "Wave of Despair", nameZh: "邀寵召禍", effectZh: "受傷後對附近造成傷害並施加虛弱。", tags: ["revenge"] },
  { id: "different-league", god: "aphrodite", slot: "extra", name: "Different League", nameZh: "高攀不起", effectZh: "抵抗近距離敵人攻擊的部分傷害。" },
  { id: "life-affirmation", god: "aphrodite", slot: "extra", name: "Life Affirmation", nameZh: "一生相伴", effectZh: "生命值房間獎勵更豐厚。" },
  { id: "empty-inside", god: "aphrodite", slot: "extra", name: "Empty Inside", nameZh: "悵然若失", effectZh: "虛弱持續更久。" },
  { id: "sweet-surrender", god: "aphrodite", slot: "extra", name: "Sweet Surrender", nameZh: "拜倒裙下", effectZh: "虛弱的敵人受到更多傷害。" },
  { id: "broken-resolve", god: "aphrodite", slot: "extra", name: "Broken Resolve", nameZh: "心旌蕩漾", effectZh: "虛弱效果更強。" },
  { id: "blown-kiss", god: "aphrodite", slot: "extra", name: "Blown Kiss", nameZh: "爆裂飛吻", effectZh: "投彈射得更遠，對未受傷敵人更強。" },
  { id: "unhealthy-fixation", god: "aphrodite", slot: "legendary", name: "Unhealthy Fixation", nameZh: "走火入魔", effectZh: "虛弱也有機率魅惑敵人。", prereq: { type: "OneFromEachSet", sets: [["empty-inside", "sweet-surrender", "broken-resolve"], ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash"]] } },

  /* ——— Artemis ——— */
  { id: "deadly-strike", god: "artemis", slot: "attack", name: "Deadly Strike", nameZh: "致命攻擊", effectZh: "攻擊更強，並有機率暴擊。" },
  { id: "deadly-flourish", god: "artemis", slot: "special", name: "Deadly Flourish", nameZh: "致命亂舞", effectZh: "特殊攻擊更強，並有機率暴擊。" },
  { id: "true-shot", god: "artemis", slot: "cast", name: "True Shot", nameZh: "會心一擊", effectZh: "投彈會追蹤敵人，並有機率暴擊。" },
  { id: "hunter-dash", god: "artemis", slot: "dash", name: "Hunter Dash", nameZh: "獵人衝刺", effectZh: "衝刺打擊造成更多傷害。", exclusiveAspects: ["lucifer"] },
  { id: "artemis-aid", god: "artemis", slot: "call", name: "Artemis' Aid", nameZh: "阿爾忒彌斯之援", effectZh: "發射高暴擊機率的追蹤箭。" },
  { id: "pressure-points", god: "artemis", slot: "extra", name: "Pressure Points", nameZh: "直指要害", effectZh: "你造成的任何傷害都有機率暴擊。" },
  { id: "exit-wounds", god: "artemis", slot: "extra", name: "Exit Wounds", nameZh: "拔箭留瘡", effectZh: "血石從敵人身上脫落時造成傷害。", soul: "infernal" },
  { id: "hide-breaker", god: "artemis", slot: "extra", name: "Hide Breaker", nameZh: "破甲暴擊", effectZh: "暴擊對護甲造成更多傷害。" },
  { id: "clean-kill", god: "artemis", slot: "extra", name: "Clean Kill", nameZh: "乾淨俐落", effectZh: "暴擊造成更多傷害。" },
  { id: "hunter-instinct", god: "artemis", slot: "extra", name: "Hunter Instinct", nameZh: "獵人本能", effectZh: "造成暴擊時神力槽充能更快。" },
  { id: "hunters-mark", god: "artemis", slot: "extra", name: "Hunter's Mark", nameZh: "獵人標記", effectZh: "對一名敵人暴擊後，附近另一名敵人被標記。" },
  { id: "support-fire", god: "artemis", slot: "extra", name: "Support Fire", nameZh: "火力支援", effectZh: "攻擊、特殊或投彈命中後，再射出追蹤箭。" },
  { id: "fully-loaded", god: "artemis", slot: "legendary", name: "Fully Loaded", nameZh: "全副武裝", effectZh: "投彈血石數量增加。", soul: "infernal", prereq: { type: "TwoOf", ids: ["exit-wounds", "support-fire", "pressure-points"] } },

  /* ——— Ares ——— */
  { id: "curse-of-agony", god: "ares", slot: "attack", name: "Curse of Agony", nameZh: "致命詛咒", effectZh: "攻擊施加厄運（Doom）。" },
  { id: "curse-of-pain", god: "ares", slot: "special", name: "Curse of Pain", nameZh: "痛苦詛咒", effectZh: "特殊攻擊施加厄運。" },
  { id: "slicing-shot", god: "ares", slot: "cast", name: "Slicing Shot", nameZh: "旋刀射擊", effectZh: "投彈向前擲出劍刃旋風（Blade Rift）。" },
  { id: "blade-dash", god: "ares", slot: "dash", name: "Blade Dash", nameZh: "利刃衝刺", effectZh: "衝刺起點產生劍刃旋風。" },
  { id: "ares-aid", god: "ares", slot: "call", name: "Ares' Aid", nameZh: "阿瑞斯之援", effectZh: "短暫化為無敵的劍刃旋風。" },
  { id: "curse-of-vengeance", god: "ares", slot: "extra", name: "Curse of Vengeance", nameZh: "復仇詛咒", effectZh: "受傷後對周圍敵人施加厄運。", tags: ["revenge"] },
  { id: "urge-to-kill", god: "ares", slot: "extra", name: "Urge to Kill", nameZh: "殺之後快", effectZh: "攻擊、特殊與投彈傷害提高。" },
  { id: "battle-rage", god: "ares", slot: "extra", name: "Battle Rage", nameZh: "血戰狂怒", effectZh: "擊殺後，下一次攻擊或特殊傷害提高。" },
  { id: "blood-frenzy", god: "ares", slot: "extra", name: "Blood Frenzy", nameZh: "血迷心竅", effectZh: "使用死亡反抗後，該場遭遇傷害提高。" },
  { id: "black-metal", god: "ares", slot: "extra", name: "Black Metal", nameZh: "黑色金屬", effectZh: "劍刃旋風範圍更大。" },
  { id: "engulfing-vortex", god: "ares", slot: "extra", name: "Engulfing Vortex", nameZh: "漩渦吞噬", effectZh: "劍刃旋風持續更久並拉近敵人。" },
  { id: "dire-misfortune", god: "ares", slot: "extra", name: "Dire Misfortune", nameZh: "滅頂之災", effectZh: "重複施加厄運時傷害更高。" },
  { id: "impending-doom", god: "ares", slot: "extra", name: "Impending Doom", nameZh: "不可終日", effectZh: "厄運傷害更高，但引爆稍慢。" },
  { id: "vicious-cycle", god: "ares", slot: "legendary", name: "Vicious Cycle", nameZh: "戰患輪迴", effectZh: "劍刃旋風連續命中傷害遞增。", prereq: { type: "OneOf", ids: ["black-metal", "engulfing-vortex"] } },

  /* ——— Dionysus ——— */
  { id: "drunken-strike", god: "dionysus", slot: "attack", name: "Drunken Strike", nameZh: "醉酒攻擊", effectZh: "攻擊施加醉酒（Hangover）。" },
  { id: "drunken-flourish", god: "dionysus", slot: "special", name: "Drunken Flourish", nameZh: "醉酒亂舞", effectZh: "特殊攻擊施加醉酒。" },
  { id: "trippy-shot", god: "dionysus", slot: "cast", name: "Trippy Shot", nameZh: "致幻射擊", effectZh: "投彈落地後爆成歡慶迷霧（Festive Fog）。" },
  { id: "drunken-dash", god: "dionysus", slot: "dash", name: "Drunken Dash", nameZh: "醉酒衝刺", effectZh: "衝刺對附近敵人施加醉酒。" },
  { id: "dionysus-aid", god: "dionysus", slot: "call", name: "Dionysus' Aid", nameZh: "迪奧尼索斯之援", effectZh: "對周圍敵人施加數秒醉酒。" },
  { id: "after-party", god: "dionysus", slot: "extra", name: "After Party", nameZh: "宴後再聚", effectZh: "遭遇結束時若生命過低，回復至門檻。" },
  { id: "positive-outlook", god: "dionysus", slot: "extra", name: "Positive Outlook", nameZh: "苦中作樂", effectZh: "低生命時受到傷害減少。" },
  { id: "premium-vintage", god: "dionysus", slot: "extra", name: "Premium Vintage", nameZh: "醇香美酒", effectZh: "拾取花蜜時獲得生命，並立即給一瓶花蜜。" },
  { id: "strong-drink", god: "dionysus", slot: "extra", name: "Strong Drink", nameZh: "烈酒入喉", effectZh: "使用噴泉回滿生命並獲得傷害加成。" },
  { id: "bad-influence", god: "dionysus", slot: "extra", name: "Bad Influence", nameZh: "惡劣影響", effectZh: "多名敵人處於醉酒時，你造成更多傷害。" },
  { id: "numbing-sensation", god: "dionysus", slot: "extra", name: "Numbing Sensation", nameZh: "爛醉如泥", effectZh: "醉酒也會使敵人移動變慢。" },
  { id: "peer-pressure", god: "dionysus", slot: "extra", name: "Peer Pressure", nameZh: "花前勸酒", effectZh: "醉酒的敵人會傳染附近敵人。" },
  { id: "high-tolerance", god: "dionysus", slot: "extra", name: "High Tolerance", nameZh: "千杯不醉", effectZh: "站在歡慶迷霧中受到傷害減少。" },
  { id: "black-out", god: "dionysus", slot: "legendary", name: "Black Out", nameZh: "不省人事", effectZh: "醉酒的敵人在迷霧中受到額外傷害。", prereq: { type: "OneFromEachSet", sets: [["trippy-shot"], ["drunken-strike", "drunken-flourish", "drunken-dash", "dionysus-aid"]] } },

  /* ——— Demeter ——— */
  { id: "frost-strike", god: "demeter", slot: "attack", name: "Frost Strike", nameZh: "冰霜攻擊", effectZh: "攻擊更強並施加冰凍（Chill）。" },
  { id: "frost-flourish", god: "demeter", slot: "special", name: "Frost Flourish", nameZh: "冰霜亂舞", effectZh: "特殊攻擊更強並施加冰凍。" },
  { id: "crystal-beam", god: "demeter", slot: "cast", name: "Crystal Beam", nameZh: "水晶射擊", effectZh: "投彈放下向前發射光束的水晶。" },
  { id: "mistral-dash", god: "demeter", slot: "dash", name: "Mistral Dash", nameZh: "冷風衝刺", effectZh: "衝刺向前射出施加冰凍的氣流。" },
  { id: "demeter-aid", god: "demeter", slot: "call", name: "Demeter's Aid", nameZh: "得墨忒爾之援", effectZh: "產生造成傷害並施加冰凍的冬日漩渦。" },
  { id: "frozen-touch", god: "demeter", slot: "extra", name: "Frozen Touch", nameZh: "冰寒之觸", effectZh: "受傷後對該敵人造成傷害並完全冰凍。", tags: ["revenge"] },
  { id: "rare-crop", god: "demeter", slot: "extra", name: "Rare Crop", nameZh: "罕見收穫", effectZh: "祝福先變為普通，之後每隔數場遭遇提升稀有度。" },
  { id: "ravenous-will", god: "demeter", slot: "extra", name: "Ravenous Will", nameZh: "求生意志", effectZh: "沒有血石時減傷並提高傷害。" },
  { id: "nourished-soul", god: "demeter", slot: "extra", name: "Nourished Soul", nameZh: "靈魂滋養", effectZh: "所有生命效果更強，並立即回復一些生命。" },
  { id: "snow-burst", god: "demeter", slot: "extra", name: "Snow Burst", nameZh: "暴風驟雪", effectZh: "投彈時對附近造成傷害並施加冰凍。" },
  { id: "arctic-blast", god: "demeter", slot: "extra", name: "Arctic Blast", nameZh: "極地風暴", effectZh: "冰凍疊滿 10 層時爆炸並清除效果。" },
  { id: "killing-freeze", god: "demeter", slot: "extra", name: "Killing Freeze", nameZh: "刺骨嚴寒", effectZh: "所有敵人都冰凍時，他們變慢並持續流失生命。" },
  { id: "glacial-glare", god: "demeter", slot: "extra", name: "Glacial Glare", nameZh: "冰川極寒", effectZh: "投彈持續更久並施加冰凍。" },
  { id: "winter-harvest", god: "demeter", slot: "legendary", name: "Winter Harvest", nameZh: "嚴冬收割", effectZh: "低生命的冰凍敵人會碎裂，對附近施加冰凍。", prereq: { type: "TwoOf", ids: ["arctic-blast", "killing-freeze", "ravenous-will"] } },

  /* ——— Hermes (no Duo) ——— */
  { id: "swift-strike", god: "hermes", slot: "extra", name: "Swift Strike", nameZh: "迅捷攻擊", effectZh: "攻擊速度提高。" },
  { id: "swift-flourish", god: "hermes", slot: "extra", name: "Swift Flourish", nameZh: "迅捷亂舞", effectZh: "特殊攻擊速度提高。" },
  { id: "flurry-cast", god: "hermes", slot: "extra", name: "Flurry Cast", nameZh: "極速投射", effectZh: "投彈更快且全自動。" },
  { id: "quick-favor", god: "hermes", slot: "extra", name: "Quick Favor", nameZh: "迅捷賜福", effectZh: "神力槽自動充能。" },
  { id: "hyper-sprint", god: "hermes", slot: "extra", name: "Hyper Sprint", nameZh: "大步流星", effectZh: "衝刺後短暫堅韌並大幅加速。" },
  { id: "greater-haste", god: "hermes", slot: "extra", name: "Greater Haste", nameZh: "健步如飛", effectZh: "移動速度提高。" },
  { id: "quick-recovery", god: "hermes", slot: "extra", name: "Quick Recovery", nameZh: "快速恢復", effectZh: "受傷後迅速衝刺可回復部分損失生命。" },
  { id: "greater-evasion", god: "hermes", slot: "extra", name: "Greater Evasion", nameZh: "閃躲騰挪", effectZh: "提高閃避機率。" },
  { id: "greatest-reflex", god: "hermes", slot: "extra", name: "Greatest Reflex", nameZh: "極速反應", effectZh: "可連續衝刺次數增加。" },
  { id: "second-wind", god: "hermes", slot: "extra", name: "Second Wind", nameZh: "越戰越勇", effectZh: "使用求援後短暫提高閃避與移速。" },
  { id: "rush-delivery", god: "hermes", slot: "extra", name: "Rush Delivery", nameZh: "欲速則達", effectZh: "依移動速度加成提高傷害。" },
  { id: "quick-reload", god: "hermes", slot: "extra", name: "Quick Reload", nameZh: "快速裝彈", effectZh: "插在敵人身上的血石更快掉落。", soul: "infernal" },
  { id: "auto-reload", god: "hermes", slot: "extra", name: "Auto Reload", nameZh: "自動填彈", effectZh: "血石自動回補更快。", soul: "stygian" },
  { id: "greater-recall", god: "hermes", slot: "legendary", name: "Greater Recall", nameZh: "自動收回", effectZh: "血石會自動回到你身邊。", soul: "infernal", prereq: { type: "OneOf", ids: ["flurry-cast", "quick-reload"], keepsakes: ["lambent-plume"] } },
  { id: "bad-news", god: "hermes", slot: "legendary", name: "Bad News", nameZh: "當頭一棒", effectZh: "對身上沒有你投彈彈藥的敵人，投彈傷害提高。", soul: "stygian", prereq: { type: "OneOf", ids: ["auto-reload"], keepsakes: ["lambent-plume"] } },
];

const DUOS = [
  {
    id: "curse-of-longing",
    name: "Curse of Longing",
    nameZh: "求而不得",
    gods: ["aphrodite", "ares"],
    effectZh: "厄運會持續打擊處於虛弱的敵人。",
    stat: "後續命中傷害 50%",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash"],
      ares: ["curse-of-agony", "curse-of-pain"],
    },
  },
  {
    id: "heart-rend",
    name: "Heart Rend",
    nameZh: "撕心裂肺",
    gods: ["aphrodite", "artemis"],
    effectZh: "暴擊對虛弱敵人造成更多傷害。",
    stat: "暴擊傷害 +150%",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash"],
      artemis: ["deadly-strike", "deadly-flourish", "true-shot"],
    },
  },
  {
    id: "parting-shot",
    name: "Parting Shot",
    nameZh: "臨別贈禮",
    gods: ["aphrodite", "athena"],
    effectZh: "投彈獲得所有背擊加成。",
    stat: "背擊傷害 +35%",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash", "aphrodite-aid"],
      athena: ["divine-strike", "divine-flourish", "phalanx-shot", "divine-dash", "athena-aid"],
    },
    incompatibleAspects: ["beowulf"],
    blockedByBoons: ["trippy-shot"],
    notes: "與貝奧武夫型態不相容；也無法與致幻射擊並存。",
  },
  {
    id: "cold-embrace",
    name: "Cold Embrace",
    nameZh: "冰寒之擁",
    gods: ["aphrodite", "demeter"],
    effectZh: "投彈水晶改為朝你發射光束，持續 +4 秒。",
    stat: "投彈傷害 +30%",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "passion-dash", "aphrodite-aid"],
      demeter: ["crystal-beam"],
    },
    incompatibleAspects: ["beowulf"],
    exclusiveWith: ["crystal-clarity"],
  },
  {
    id: "low-tolerance",
    name: "Low Tolerance",
    nameZh: "縱情酒色",
    gods: ["aphrodite", "dionysus"],
    effectZh: "對虛弱敵人，醉酒可疊加更多層。",
    stat: "對虛弱最大層數 +3",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash"],
      dionysus: ["drunken-strike", "drunken-flourish", "drunken-dash", "dionysus-aid"],
    },
  },
  {
    id: "sweet-nectar",
    name: "Sweet Nectar",
    nameZh: "甘甜蜜露",
    gods: ["aphrodite", "poseidon"],
    effectZh: "找到的力量石榴更有效。",
    stat: "石榴額外 +1 級",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash", "aphrodite-aid"],
      poseidon: ["tempest-strike", "tempest-flourish", "flood-shot", "tidal-dash", "poseidon-aid"],
    },
  },
  {
    id: "smoldering-air",
    name: "Smoldering Air",
    nameZh: "煙燻火燎",
    gods: ["aphrodite", "zeus"],
    effectZh: "神力槽自動充能，但上限為 25%。",
    stat: "每 0.2 秒 +1%",
    req: {
      aphrodite: ["heartbreak-strike", "heartbreak-flourish", "crush-shot", "passion-dash", "aphrodite-aid"],
      zeus: ["lightning-strike", "thunder-flourish", "electric-shot", "thunder-dash", "zeus-aid"],
    },
    extraReq: "non-hades-aid",
    notes: "需要非黑帝斯的求援（Aid）。",
  },
  {
    id: "hunting-blades",
    name: "Hunting Blades",
    nameZh: "狩獵之刃",
    gods: ["ares", "artemis"],
    effectZh: "投彈化為更快、會追蹤最近敵人的劍刃旋風。",
    stat: "追蹤 3.3 秒",
    req: {
      ares: ["slicing-shot"],
      artemis: ["deadly-strike", "deadly-flourish", "hunter-dash", "artemis-aid"],
    },
    incompatibleAspects: ["beowulf"],
    exclusiveWith: ["freezing-vortex"],
  },
  {
    id: "merciful-end",
    name: "Merciful End",
    nameZh: "仁慈解脫",
    gods: ["ares", "athena"],
    effectZh: "可反彈的技能會立即引爆厄運。",
    stat: "連擊傷害 40",
    req: {
      ares: ["curse-of-agony", "curse-of-pain"],
      athena: ["divine-strike", "divine-flourish"],
    },
  },
  {
    id: "freezing-vortex",
    name: "Freezing Vortex",
    nameZh: "冰寒風暴",
    gods: ["ares", "demeter"],
    effectZh: "投彈施加冰凍，但裂隙更小、移動更慢。",
    stat: "裂隙大小 -15%",
    req: {
      ares: ["slicing-shot"],
      demeter: ["frost-strike", "frost-flourish", "mistral-dash", "demeter-aid"],
    },
    exclusiveWith: ["hunting-blades"],
  },
  {
    id: "curse-of-nausea",
    name: "Curse of Nausea",
    nameZh: "嘔吐詛咒",
    gods: ["ares", "dionysus"],
    effectZh: "醉酒傷害跳得更快。",
    stat: "0.5 秒 → 0.35 秒",
    req: {
      ares: ["curse-of-agony", "curse-of-pain", "curse-of-vengeance"],
      dionysus: ["drunken-strike", "drunken-flourish", "drunken-dash", "dionysus-aid"],
    },
  },
  {
    id: "curse-of-drowning",
    name: "Curse of Drowning",
    nameZh: "溺亡詛咒",
    gods: ["ares", "poseidon"],
    effectZh: "投彈化為環繞你的脈衝傷害。",
    stat: "每次投彈 3 波",
    req: {
      ares: ["curse-of-agony", "curse-of-pain", "blade-dash", "ares-aid"],
      poseidon: ["flood-shot"],
    },
    incompatibleAspects: ["hera"],
    exclusiveWith: ["mirage-shot", "blizzard-shot", "ice-wine"],
  },
  {
    id: "vengeful-mood",
    name: "Vengeful Mood",
    nameZh: "睚眥必報",
    gods: ["ares", "zeus"],
    effectZh: "復仇效果有時不需受傷也會觸發。",
    stat: "每 3 秒自動復仇",
    req: {
      ares: ["curse-of-agony", "curse-of-pain", "slicing-shot", "blade-dash", "ares-aid"],
      zeus: ["lightning-strike", "thunder-flourish", "electric-shot", "thunder-dash", "zeus-aid"],
    },
    extraReq: "revenge",
    notes: "另外需要任一復仇祝福：邀寵召禍、復仇詛咒、神聖盾衛、冰寒之觸、雷神懲擊。",
  },
  {
    id: "deadly-reversal",
    name: "Deadly Reversal",
    nameZh: "致命還擊",
    gods: ["artemis", "athena"],
    effectZh: "反彈後短暫獲得暴擊機率。",
    stat: "+20% 暴擊，持續 2 秒",
    req: {
      artemis: ["deadly-strike", "deadly-flourish", "true-shot", "artemis-aid"],
      athena: ["divine-strike", "divine-flourish"],
    },
  },
  {
    id: "crystal-clarity",
    name: "Crystal Clarity",
    nameZh: "冰寒射線",
    gods: ["artemis", "demeter"],
    effectZh: "投彈更強，且更精準追蹤敵人。",
    stat: "光束傷害 +10%",
    req: {
      artemis: ["deadly-strike", "deadly-flourish", "hunter-dash", "artemis-aid"],
      demeter: ["crystal-beam"],
    },
    incompatibleAspects: ["beowulf"],
    exclusiveWith: ["cold-embrace"],
  },
  {
    id: "splitting-headache",
    name: "Splitting Headache",
    nameZh: "頭痛欲裂",
    gods: ["artemis", "dionysus"],
    effectZh: "醉酒的敵人更容易被暴擊。",
    stat: "每層醉酒 +1.5% 暴擊",
    req: {
      artemis: ["deadly-strike", "deadly-flourish", "true-shot", "artemis-aid"],
      dionysus: ["drunken-strike", "drunken-flourish", "drunken-dash", "dionysus-aid"],
    },
    ignoreReqIfAspect: { beowulf: ["true-shot"] },
    notes: "貝奧武夫的獵人爆破不計入此雙重祝福的阿爾忒彌斯條件。",
  },
  {
    id: "mirage-shot",
    name: "Mirage Shot",
    nameZh: "蜃氣射擊",
    gods: ["artemis", "poseidon"],
    effectZh: "投彈額外射出一發較弱的投射物。",
    stat: "第二發射擊傷害 30%",
    req: {
      artemis: ["deadly-strike", "deadly-flourish", "true-shot", "artemis-aid"],
      poseidon: ["tempest-strike", "tempest-flourish", "flood-shot", "tidal-dash", "poseidon-aid"],
    },
    exclusiveWith: ["curse-of-drowning"],
  },
  {
    id: "lightning-rod",
    name: "Lightning Rod",
    nameZh: "引電血統",
    gods: ["artemis", "zeus"],
    effectZh: "地上的血石每秒對附近敵人打雷。",
    stat: "閃電傷害 70",
    req: {
      artemis: ["deadly-strike", "deadly-flourish", "true-shot", "hunter-dash", "artemis-aid"],
      zeus: ["lightning-strike", "thunder-flourish", "electric-shot", "thunder-dash", "zeus-aid"],
    },
    extraReq: "infernal-soul",
    notes: "需要夜之聖鏡「煉獄靈魂」（血石會掉落）。與冥河靈魂不相容。切換夜之聖鏡後會自動判定。",
  },
  {
    id: "stubborn-roots",
    name: "Stubborn Roots",
    nameZh: "根深蒂固",
    gods: ["athena", "demeter"],
    effectZh: "若沒有死亡／頑強反抗，戰鬥中緩慢回血。",
    stat: "每 0.8 秒回復 1 生命",
    req: {
      athena: ["divine-strike", "divine-flourish", "phalanx-shot", "divine-dash", "athena-aid"],
      demeter: ["frost-strike", "frost-flourish", "crystal-beam", "mistral-dash", "demeter-aid"],
    },
  },
  {
    id: "calculated-risk",
    name: "Calculated Risk",
    nameZh: "風險管理",
    gods: ["athena", "dionysus"],
    effectZh: "敵人遠程投射物變慢。",
    stat: "投射物速度 -50%",
    req: {
      athena: ["divine-strike", "divine-flourish", "divine-dash", "athena-aid"],
      dionysus: ["drunken-strike", "drunken-flourish", "drunken-dash", "dionysus-aid"],
    },
  },
  {
    id: "unshakable-mettle",
    name: "Unshakable Mettle",
    nameZh: "無匹之力",
    gods: ["athena", "poseidon"],
    effectZh: "不會被暈眩，並抵抗部分首領傷害。",
    stat: "首領減傷 10%",
    req: {
      athena: ["divine-strike", "divine-flourish", "phalanx-shot", "athena-aid"],
      poseidon: ["tempest-strike", "tempest-flourish", "flood-shot", "poseidon-aid"],
    },
  },
  {
    id: "lightning-phalanx",
    name: "Lightning Phalanx",
    nameZh: "閃電殺陣",
    gods: ["athena", "zeus"],
    effectZh: "殺陣射擊會在附近敵人間彈跳。",
    stat: "最多彈跳 3 次",
    req: {
      athena: ["phalanx-shot"],
      zeus: ["lightning-strike", "thunder-flourish", "thunder-dash", "zeus-aid"],
    },
    incompatibleAspects: ["beowulf"],
  },
  {
    id: "ice-wine",
    name: "Ice Wine",
    nameZh: "寒冰美酒",
    gods: ["demeter", "dionysus"],
    effectZh: "投彈以冰凍歡慶迷霧爆破範圍，並施加冰凍。",
    stat: "爆破傷害 +30%",
    req: {
      demeter: ["frost-strike", "frost-flourish", "mistral-dash", "demeter-aid"],
      dionysus: ["trippy-shot"],
    },
    exclusiveWith: ["curse-of-drowning", "blizzard-shot"],
  },
  {
    id: "blizzard-shot",
    name: "Blizzard Shot",
    nameZh: "暴雪射擊",
    gods: ["demeter", "poseidon"],
    effectZh: "投彈緩慢前進、穿透敵人，並向周圍射出冰晶。",
    stat: "冰晶傷害 40",
    req: {
      demeter: ["frost-strike", "frost-flourish", "mistral-dash", "demeter-aid"],
      poseidon: ["flood-shot"],
    },
    incompatibleAspects: ["beowulf"],
    exclusiveWith: ["curse-of-drowning", "ice-wine"],
  },
  {
    id: "cold-fusion",
    name: "Cold Fusion",
    nameZh: "冷酷聚變",
    gods: ["demeter", "zeus"],
    effectZh: "心驚膽戰效果不會因敵人攻擊而結束。",
    stat: "心驚膽戰持續 10 秒",
    req: {
      demeter: ["frost-strike", "frost-flourish", "mistral-dash", "demeter-aid"],
      zeus: ["static-discharge"],
    },
  },
  {
    id: "exclusive-access",
    name: "Exclusive Access",
    nameZh: "專屬體驗",
    gods: ["dionysus", "poseidon"],
    effectZh: "之後找到的祝福效果更強（至少史詩）。",
    stat: "最低稀有度：史詩",
    req: {
      dionysus: ["drunken-strike", "drunken-flourish", "trippy-shot", "drunken-dash", "dionysus-aid"],
      poseidon: ["tempest-strike", "tempest-flourish", "flood-shot", "tidal-dash", "poseidon-aid"],
    },
  },
  {
    id: "scintillating-feast",
    name: "Scintillating Feast",
    nameZh: "光輝盛宴",
    gods: ["dionysus", "zeus"],
    effectZh: "歡慶迷霧會週期性造成閃電傷害。",
    stat: "閃電傷害 60",
    req: {
      dionysus: ["trippy-shot"],
      zeus: ["lightning-strike", "thunder-flourish", "thunder-dash", "zeus-aid"],
    },
    incompatibleAspects: ["beowulf"],
  },
  {
    id: "sea-storm",
    name: "Sea Storm",
    nameZh: "海上風暴",
    gods: ["poseidon", "zeus"],
    effectZh: "擊退敵人時，他們會被閃電擊中。",
    stat: "閃電傷害 40",
    req: {
      poseidon: ["tempest-strike", "tempest-flourish", "flood-shot", "poseidon-aid"],
      zeus: ["lightning-strike", "thunder-flourish", "electric-shot", "thunder-dash", "zeus-aid"],
    },
    notes: "盾的攻擊、劍的突刺與特殊等非祝福擊退也會觸發。",
  },
];

const WEAPONS = [
  {
    id: "stygius",
    name: "Stygius",
    subtitle: "the Stygian Blade",
    nameZh: "冥界之刃",
    former: "Poseidon",
    formerZh: "波塞冬",
    unlock: "開局即擁有",
    keys: 0,
    accent: "#c23b3b",
    playstyle: "近戰均衡",
    desc: "三連斬的中距離長劍。特殊攻擊短跳後在身邊爆發，落地短暫停頓。",
    moves: {
      attack: { nameZh: "三連斬", damage: "20 · 25 · 30" },
      special: { nameZh: "新星粉碎", damage: "50", noteZh: "落地短暫停頓" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "提高移動速度與衝刺距離。",
        levels: "移速／衝刺 +3% → +15%",
        playstyle: "均衡機動",
        gods: ["aphrodite", "athena", "artemis"],
        slots: { attack: "heartbreak-strike", special: "deadly-flourish", dash: "divine-dash" },
        duos: ["heart-rend", "deadly-reversal", "merciful-end"],
        notes: "萬用起步。神聖衝刺幾乎必拿；攻擊放虛弱或暴擊都穩。劍本身有擊退，海上風暴也很好用。",
      },
      {
        id: "nemesis",
        name: "Nemesis",
        nameZh: "涅墨西斯",
        hidden: false,
        effectZh: "特殊攻擊後 3 秒內，攻擊有機率暴擊。",
        levels: "暴擊機率 15% → 30%",
        playstyle: "暴擊連段",
        gods: ["artemis", "aphrodite", "athena"],
        slots: { attack: "deadly-strike", special: "heartbreak-flourish", dash: "divine-dash" },
        duos: ["heart-rend", "deadly-reversal"],
        notes: "核心是特殊後普攻吃暴擊。阿爾忒彌斯攻擊 + 阿弗洛狄忒虛弱可衝撕心裂肺。潔淨擊殺、要害都是強補。",
        moves: {
          special: { nameZh: "新星粉碎", damage: "50", noteZh: "特殊後普攻可暴擊" },
        },
      },
      {
        id: "poseidon",
        name: "Poseidon",
        nameZh: "波塞冬",
        hidden: false,
        effectZh: "特殊攻擊會把敵人身上的投彈彈藥打出來。",
        levels: "投彈傷害 +10% → +50%",
        playstyle: "投彈回收",
        gods: ["artemis", "poseidon", "zeus"],
        slots: { special: "tempest-flourish", cast: "true-shot", dash: "divine-dash" },
        duos: ["mirage-shot", "sea-storm", "lightning-rod"],
        notes: "把血石打進敵人再特殊打出，觸發拔箭留瘡。夜之聖鏡若選煉獄靈魂，引電血統極強。",
        moves: {
          special: { nameZh: "新星粉碎", damage: "50", noteZh: "打出敵人身上的投彈" },
        },
      },
      {
        id: "arthur",
        name: "Arthur",
        nameZh: "亞瑟",
        hidden: true,
        unlockZh: "向妮克斯學習密語：「我看見你自石牢獲赦的王者寬恕。」需已揭示關羽，並在劍型態投入 5 泰坦之血。",
        effectZh: "化為聖劍Excalibur，+50 生命，並擁有減傷光環。招式變慢、範圍變大。",
        levels: "光環減傷 20% → 40%",
        playstyle: "緩慢坦克",
        gods: ["athena", "aphrodite", "demeter"],
        slots: { attack: "heartbreak-strike", dash: "divine-dash", special: "frost-flourish" },
        duos: ["stubborn-roots", "unshakable-mettle", "calculated-risk"],
        notes: "動作慢，神聖衝刺幾乎不可缺。光環減傷讓生存向祝福（得墨忒爾、迪奧尼索斯、雅典娜）價值更高。",
        moves: {
          attack: { nameZh: "重斬", damage: "60" },
          special: { nameZh: "聖域新星", damage: "70", noteZh: "減傷光環" },
        },
      },
    ],
  },
  {
    id: "varatha",
    name: "Varatha",
    subtitle: "the Eternal Spear",
    nameZh: "永恆之矛",
    former: "Hades",
    formerZh: "黑帝斯",
    unlock: "4 冥府鑰匙",
    keys: 4,
    accent: "#2f9e6a",
    playstyle: "中遠距突刺",
    desc: "可蓄力迴旋斬的長槍。特殊攻擊把槍擲出，再按一次召回，來回都會傷害敵人。",
    moves: {
      attack: { nameZh: "突刺", damage: "25" },
      special: { nameZh: "擲槍", damage: "45", noteZh: "召回再傷一次" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "提高射程、速度與特殊傷害。",
        levels: "+10% → +25%",
        playstyle: "均衡長槍",
        gods: ["aphrodite", "athena", "artemis"],
        slots: { attack: "heartbreak-strike", special: "deadly-flourish", dash: "divine-dash" },
        duos: ["heart-rend", "deadly-reversal"],
        notes: "標準近戰配裝。擲槍特殊很適合暴擊或虛弱。",
      },
      {
        id: "achilles",
        name: "Achilles",
        nameZh: "阿喀琉斯",
        hidden: false,
        effectZh: "特殊攻擊後可用狂怒衝刺取回長槍。",
        levels: "衝刺後傷害 +50% → +150%",
        playstyle: "擲槍衝刺",
        gods: ["aphrodite", "artemis", "athena"],
        slots: { special: "heartbreak-flourish", attack: "deadly-strike", dash: "divine-dash" },
        duos: ["heart-rend", "deadly-reversal", "merciful-end"],
        notes: "擲槍 → 衝刺取回 → 強化普攻。特殊放虛弱或暴擊都強；赫爾墨斯的迅捷亂舞很香。",
        moves: {
          special: { nameZh: "擲槍", damage: "45", noteZh: "衝刺取回後強化普攻" },
        },
      },
      {
        id: "hades",
        name: "Hades",
        nameZh: "黑帝斯",
        hidden: false,
        effectZh: "迴旋斬變為懲罰橫掃，範圍更大。",
        levels: "橫掃傷害 +30% → +150%",
        playstyle: "迴旋橫掃",
        gods: ["ares", "dionysus", "poseidon"],
        slots: { attack: "curse-of-agony", special: "drunken-flourish", dash: "tidal-dash" },
        duos: ["curse-of-longing", "curse-of-nausea", "sea-storm"],
        notes: "橫掃一次打中多人，厄運與醉酒都能快速上狀態。波塞冬攻擊可觸發海上風暴。",
        moves: {
          attack: { nameZh: "懲罰橫掃", damage: "25", noteZh: "迴旋改為大範圍橫掃" },
        },
      },
      {
        id: "guan-yu",
        name: "Guan Yu",
        nameZh: "關羽",
        hidden: true,
        unlockZh: "向阿喀琉斯學習密語：「我透過緋紅鳳凰之眼看見你。」需解鎖 5 個非札格列歐斯型態、抵達最終首領，並解鎖命運清單。",
        effectZh: "化為霜公平刃，生命與治療大幅降低；特殊變為旋轉拉近。",
        levels: "生命／回復 -70% → -50%",
        playstyle: "高危多段",
        gods: ["dionysus", "aphrodite", "athena"],
        slots: { special: "drunken-flourish", attack: "heartbreak-strike", dash: "divine-dash" },
        duos: ["low-tolerance", "curse-of-nausea", "stubborn-roots"],
        notes: "生命極低，神聖衝刺與回復向祝福很重要。特殊多段極適合疊醉酒。",
        moves: {
          attack: { nameZh: "霜公平刃", damage: "多段" },
          special: { nameZh: "旋轉拉近", damage: "多段", noteZh: "生命與治療大幅降低" },
        },
      },
    ],
  },
  {
    id: "aegis",
    name: "Aegis",
    subtitle: "the Shield of Chaos",
    nameZh: "混沌之盾",
    former: "Zeus",
    formerZh: "宙斯",
    unlock: "3 冥府鑰匙",
    keys: 3,
    accent: "#c9a227",
    playstyle: "防禦反擊",
    desc: "揮擊帶擊退；長按格擋並蓄力公牛衝鋒。特殊把盾擲出，在敵人間彈跳後返回。",
    moves: {
      attack: { nameZh: "盾擊", damage: "25", noteZh: "天生擊退" },
      special: { nameZh: "擲盾", damage: "15", noteZh: "彈跳後返回" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "受到的傷害減少。",
        levels: "減傷 5% → 10%",
        playstyle: "穩健格擋",
        gods: ["poseidon", "zeus", "athena"],
        slots: { attack: "tempest-strike", special: "thunder-flourish", dash: "divine-dash" },
        duos: ["sea-storm", "unshakable-mettle"],
        notes: "盾普攻天生擊退，海上風暴幾乎是招牌雙重。宙斯特殊讓擲盾更痛。",
      },
      {
        id: "chaos",
        name: "Chaos",
        nameZh: "卡俄斯",
        hidden: false,
        effectZh: "公牛衝鋒後，下一次特殊會擲出多面盾。",
        levels: "額外盾 1 → 5",
        playstyle: "多重擲盾",
        gods: ["zeus", "artemis", "dionysus"],
        slots: { special: "thunder-flourish", attack: "deadly-strike", dash: "divine-dash" },
        duos: ["deadly-reversal", "scintillating-feast"],
        notes: "衝鋒後特殊變成彈幕。宙斯或阿爾忒彌斯特殊最賺；迪奧尼索斯特殊可讓每面盾上醉酒。",
        moves: {
          special: { nameZh: "多重擲盾", damage: "15", noteZh: "衝鋒後一次擲出多面盾" },
        },
      },
      {
        id: "zeus",
        name: "Zeus",
        nameZh: "宙斯",
        hidden: false,
        effectZh: "特殊改為閃電圓盤，穿透敵人並停在遠處，召回時再傷一次。",
        levels: "圓盤傷害 8 → 30",
        playstyle: "持續圓盤",
        gods: ["zeus", "dionysus", "poseidon"],
        slots: { special: "thunder-flourish", attack: "tempest-strike", dash: "tidal-dash" },
        duos: ["sea-storm", "cold-fusion", "exclusive-access"],
        notes: "把圓盤停在敵人堆裡持續輸出。靜電釋放 + 冷酷聚變讓心驚膽戰常駐。",
        moves: {
          special: { nameZh: "閃電圓盤", damage: "8 → 30", noteZh: "穿透，召回再傷一次" },
        },
      },
      {
        id: "beowulf",
        name: "Beowulf",
        nameZh: "貝奧武夫",
        hidden: true,
        unlockZh: "向卡俄斯學習密語：「我看見你挺身對抗巨蛇之焰。」需已揭示關羽、持盾與卡俄斯對話，並在盾型態投入 5 泰坦之血。",
        effectZh: "化為納格林之板，受傷 +10%。公牛衝鋒會消耗血石變成龍之衝鋒（裝填投彈）。",
        levels: "龍之衝鋒 +20% → +100%",
        playstyle: "裝填投彈",
        gods: ["aphrodite", "poseidon", "zeus"],
        slots: { cast: "crush-shot", attack: "tempest-strike", dash: "divine-dash" },
        duos: ["exclusive-access", "ice-wine", "curse-of-drowning", "sweet-nectar"],
        notes: "許多投射投彈雙重無法使用（臨別贈禮、冰寒之擁、冰寒射線、狩獵之刃、閃電殺陣、暴雪射擊、光輝盛宴）。改拿爆破投彈：傾心／洪水／雷霆／致幻／水晶。",
        warnings: ["beowulf"],
        moves: {
          special: { nameZh: "擲盾", damage: "15", noteZh: "公牛衝鋒改為龍之衝鋒（裝填投彈）" },
        },
      },
    ],
  },
  {
    id: "coronacht",
    name: "Coronacht",
    subtitle: "the Heart-Seeking Bow",
    nameZh: "索心弓",
    former: "Hera",
    formerZh: "赫拉",
    unlock: "1 冥府鑰匙",
    keys: 1,
    accent: "#7cb342",
    playstyle: "遠程蓄力",
    desc: "可蓄力的遠程攻擊，完美釋放傷害更高。特殊呈扇形射出多支箭。",
    moves: {
      attack: { nameZh: "蓄力射擊", damage: "20", noteZh: "完美釋放更高" },
      special: { nameZh: "扇形齊射", damage: "10 × 5" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "攻擊有額外暴擊機率。",
        levels: "暴擊 +2% → +10%",
        playstyle: "蓄力暴擊",
        gods: ["artemis", "aphrodite", "zeus"],
        slots: { attack: "deadly-strike", special: "heartbreak-flourish", dash: "tidal-dash" },
        duos: ["heart-rend", "lightning-rod", "mirage-shot"],
        notes: "完美蓄力吃暴擊。支援射擊與潔淨擊殺是弓的好朋友。",
      },
      {
        id: "chiron",
        name: "Chiron",
        nameZh: "喀戎",
        hidden: false,
        effectZh: "特殊會自動追蹤最近一次被攻擊打中的敵人。",
        levels: "特殊箭數 3 → 7",
        playstyle: "標記連射",
        gods: ["aphrodite", "dionysus", "artemis"],
        slots: { attack: "deadly-strike", special: "heartbreak-flourish", dash: "divine-dash" },
        duos: ["heart-rend", "low-tolerance", "splitting-headache"],
        notes: "普攻點名，特殊全部送進同一目標。特殊放虛弱或醉酒能瞬間疊滿狀態。",
        moves: {
          special: { nameZh: "追蹤齊射", damage: "10 × 3 → 7", noteZh: "打進最近被普攻命中的敵人" },
        },
      },
      {
        id: "hera",
        name: "Hera",
        nameZh: "赫拉",
        hidden: false,
        effectZh: "投彈會裝填到下一次攻擊，命中時發射。",
        levels: "彈藥脫落 10 秒 → 5 秒",
        playstyle: "裝填射擊",
        gods: ["zeus", "ares", "dionysus"],
        slots: { cast: "electric-shot", attack: "deadly-strike", special: "curse-of-pain" },
        duos: ["hunting-blades", "scintillating-feast", "exclusive-access"],
        notes: "溺亡詛咒與此型態不相容。把宙斯／阿瑞斯／迪奧尼索斯投彈裝進箭裡。",
        warnings: ["hera"],
      },
      {
        id: "rama",
        name: "Rama",
        nameZh: "羅摩",
        hidden: true,
        unlockZh: "向阿爾忒彌斯學習密語：「我看見你被第七化身的臂彎拉滿。」需已揭示關羽、持弓與阿爾忒彌斯對話，並在弓型態投入 5 泰坦之血。",
        effectZh: "化為天界舍蘭伽，可使敵人共享苦難（Shared Suffering）。",
        levels: "共享傷害 30% → 60%",
        playstyle: "擴散狀態",
        gods: ["ares", "aphrodite", "artemis"],
        slots: { attack: "curse-of-agony", special: "heartbreak-flourish", dash: "divine-dash" },
        duos: ["curse-of-longing", "heart-rend"],
        notes: "共享苦難讓厄運與虛弱在敵人之間傳開。求而不得是招牌。",
        moves: {
          attack: { nameZh: "舍蘭伽", damage: "20", noteZh: "共享苦難" },
        },
      },
    ],
  },
  {
    id: "malphon",
    name: "Malphon",
    subtitle: "the Twin Fists",
    nameZh: "雙子之拳",
    former: "Demeter",
    formerZh: "得墨忒爾",
    unlock: "8 冥府鑰匙（需先解鎖前四把武器）",
    keys: 8,
    accent: "#d4782a",
    playstyle: "近身連打",
    desc: "極快的近戰連擊。特殊為二段上鉤拳；衝刺中使用特殊會更快但只打一段。",
    moves: {
      attack: { nameZh: "連拳", damage: "15 · 20 · 25" },
      special: { nameZh: "上鉤拳", damage: "30 · 40", noteZh: "衝刺中只打一段" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "提高閃避機率。",
        levels: "閃避 +5% → +15%",
        playstyle: "閃避連打",
        gods: ["aphrodite", "dionysus", "athena"],
        slots: { attack: "heartbreak-strike", special: "drunken-flourish", dash: "divine-dash" },
        duos: ["low-tolerance", "heart-rend", "calculated-risk"],
        notes: "攻速極高，虛弱與醉酒疊得飛快。赫爾墨斯迅捷攻擊與閃躲騰挪很搭。",
      },
      {
        id: "talos",
        name: "Talos",
        nameZh: "塔洛斯",
        hidden: false,
        effectZh: "特殊改為磁力切割，拉近敵人；隨後短暫強化攻擊與投彈。",
        levels: "攻擊／投彈 +8% → +40%",
        playstyle: "拉扯連打",
        gods: ["poseidon", "zeus", "aphrodite"],
        slots: { special: "tempest-flourish", attack: "lightning-strike", dash: "tidal-dash" },
        duos: ["sea-storm", "cold-fusion", "sweet-nectar"],
        notes: "把敵人拉成一堆再輸出。波塞冬特殊 + 宙斯攻擊可衝海上風暴。",
        moves: {
          special: { nameZh: "磁力切割", damage: "30", noteZh: "拉近敵人，隨後強化攻擊" },
        },
      },
      {
        id: "demeter",
        name: "Demeter",
        nameZh: "得墨忒爾",
        hidden: false,
        effectZh: "命中 12 次後，下一次特殊會多打數段。",
        levels: "額外段數 +1 → +5",
        playstyle: "蓄力特殊",
        gods: ["dionysus", "ares", "aphrodite"],
        slots: { special: "drunken-flourish", attack: "heartbreak-strike", dash: "divine-dash" },
        duos: ["curse-of-nausea", "low-tolerance", "curse-of-longing"],
        notes: "強化特殊是爆發窗。醉酒或厄運放在特殊上，一次打滿層數。",
      },
      {
        id: "gilgamesh",
        name: "Gilgamesh",
        nameZh: "吉爾伽美什",
        hidden: true,
        unlockZh: "向阿斯忒里翁學習密語：「我看見你征服荒野並與死亡和解。」需已揭示關羽、獨自面對牛頭人時持拳對話，並在拳型態投入 5 泰坦之血。",
        effectZh: "化為恩基杜之爪，衝刺上鉤可施加重創（Maim）。",
        levels: "重創傷害 100 → 400",
        playstyle: "重創遊走",
        gods: ["aphrodite", "artemis", "athena"],
        slots: { attack: "heartbreak-strike", special: "deadly-flourish", dash: "divine-dash" },
        duos: ["heart-rend", "deadly-reversal", "merciful-end"],
        notes: "重創讓敵人輸出更高也更脆。攻擊放虛弱，配合暴擊或反彈都很強。",
        moves: {
          special: { nameZh: "衝刺上鉤", damage: "30 · 40", noteZh: "可施加重創" },
        },
      },
    ],
  },
  {
    id: "exagryph",
    name: "Exagryph",
    subtitle: "the Adamant Rail",
    nameZh: "獅鷲堅砲",
    former: "Hestia",
    formerZh: "赫斯提亞",
    unlock: "8 冥府鑰匙（需解鎖其餘所有武器）",
    keys: 8,
    accent: "#e8d48b",
    playstyle: "遠程火器",
    desc: "點射或全自動射擊，打空需裝填。特殊發射延遲落地的範圍榴彈。",
    moves: {
      attack: { nameZh: "點射", damage: "10" },
      special: { nameZh: "榴彈", damage: "80", noteZh: "延遲落地" },
    },
    aspects: [
      {
        id: "zagreus",
        name: "Zagreus",
        nameZh: "札格列歐斯",
        hidden: false,
        effectZh: "提高最大彈藥。",
        levels: "彈藥 +4 → +12",
        playstyle: "彈幕壓制",
        gods: ["zeus", "artemis", "poseidon"],
        slots: { attack: "lightning-strike", special: "deadly-flourish", dash: "tidal-dash" },
        duos: ["sea-storm", "lightning-rod"],
        notes: "宙斯攻擊讓每發子彈連鎖閃電。火力支援幾乎是砲的必備其他祝福。",
      },
      {
        id: "eris",
        name: "Eris",
        nameZh: "厄里斯",
        hidden: false,
        effectZh: "吸收自己特殊的爆炸後 8 秒內提高傷害。",
        levels: "傷害 +15% → +75%",
        playstyle: "自爆強化",
        gods: ["zeus", "aphrodite", "poseidon"],
        slots: { attack: "lightning-strike", special: "tempest-flourish", dash: "divine-dash" },
        duos: ["sea-storm", "smoldering-air", "heart-rend"],
        notes: "對腳下丟榴彈吃強化，再全自動掃射。宙斯或阿弗洛狄忒攻擊最賺。",
      },
      {
        id: "hestia",
        name: "Hestia",
        nameZh: "赫斯提亞",
        hidden: false,
        effectZh: "手動裝填後，下一發射擊被強化。",
        levels: "強化彈傷害 50 → 150",
        playstyle: "一擊脫離",
        gods: ["artemis", "aphrodite", "ares"],
        slots: { attack: "deadly-strike", special: "curse-of-pain", dash: "divine-dash" },
        duos: ["heart-rend", "curse-of-longing"],
        notes: "打一發強化彈就裝填。暴擊與虛弱放大單發傷害；阿瑞斯特殊可在風箏時上厄運。",
        moves: {
          attack: { nameZh: "強化彈", damage: "10", noteZh: "手動裝填後下一發 50 → 150" },
        },
      },
      {
        id: "lucifer",
        name: "Lucifer",
        nameZh: "路西法",
        hidden: true,
        unlockZh: "向宙斯學習密語：「我看見你驕傲地自天堂墜入火焰。」需已揭示關羽、持砲與宙斯對話，並在砲型態投入 5 泰坦之血。",
        effectZh: "化為伊格涅斯伊甸，攻擊改為持續光束；特殊改為地獄火。",
        levels: "地獄火傷害 50 → 100",
        playstyle: "光束灼燒",
        gods: ["dionysus", "zeus", "poseidon"],
        slots: { attack: "drunken-strike", special: "thunder-flourish", dash: "tidal-dash" },
        duos: ["curse-of-nausea", "low-tolerance", "sea-storm"],
        notes: "獵人衝刺與此型態不相容。光束可持續疊醉酒；宙斯攻擊讓光束不斷閃電。",
        warnings: ["lucifer"],
        moves: {
          attack: { nameZh: "持續光束", damage: "持續" },
          special: { nameZh: "地獄火", damage: "50 → 100" },
        },
      },
    ],
  },
];

const REGIONS = [
  { id: "tartarus", nameZh: "塔爾塔洛斯" },
  { id: "asphodel", nameZh: "阿斯弗德爾" },
  { id: "elysium", nameZh: "極樂原" },
  { id: "styx", nameZh: "冥河" },
  { id: "temple", nameZh: "冥府聖殿" },
];

const KEEPSAKES = [
  { id: "thunder-signet", name: "Thunder Signet", nameZh: "雷霆之印", god: "zeus", type: "god", effectZh: "下一次祝福必為宙斯。" },
  { id: "conch-shell", name: "Conch Shell", nameZh: "海螺殼", god: "poseidon", type: "god", effectZh: "下一次祝福必為波塞冬。" },
  { id: "owl-pendant", name: "Owl Pendant", nameZh: "貓頭鷹吊墜", god: "athena", type: "god", effectZh: "下一次祝福必為雅典娜。" },
  { id: "eternal-rose", name: "Eternal Rose", nameZh: "永恆的玫瑰", god: "aphrodite", type: "god", effectZh: "下一次祝福必為阿弗洛狄忒。" },
  { id: "adamant-arrowhead", name: "Adamant Arrowhead", nameZh: "堅硬箭頭", god: "artemis", type: "god", effectZh: "下一次祝福必為阿爾忒彌斯。" },
  { id: "blood-filled-vial", name: "Blood-Filled Vial", nameZh: "充血藥瓶", god: "ares", type: "god", effectZh: "下一次祝福必為阿瑞斯。" },
  { id: "overflowing-cup", name: "Overflowing Cup", nameZh: "滿溢酒杯", god: "dionysus", type: "god", effectZh: "下一次祝福必為迪奧尼索斯。" },
  { id: "frostbitten-horn", name: "Frostbitten Horn", nameZh: "冰凍之角", god: "demeter", type: "god", effectZh: "下一次祝福必為得墨忒爾。" },
  { id: "lambent-plume", name: "Lambent Plume", nameZh: "螢光羽毛", god: "hermes", type: "utility", effectZh: "快速清場疊閃避與移速；也可作為自動收回或當頭一棒的前置。" },
  { id: "lucky-tooth", name: "Lucky Tooth", nameZh: "幸運牙齒", type: "utility", effectZh: "死亡反抗用盡後再給一層。" },
  { id: "evergreen-acorn", name: "Evergreen Acorn", nameZh: "常綠橡子", type: "utility", effectZh: "首領戰前幾次傷害無效。" },
  { id: "cosmic-egg", name: "Cosmic Egg", nameZh: "宇宙之卵", type: "utility", effectZh: "下一次祝福必為卡俄斯。" },
];

const HAMMERS = [
  { id: "stygius-double-edge", weapon: "stygius", name: "Double Edge", nameZh: "雙刃擊劍", effectZh: "衝刺攻擊打兩下，並提高 20% 傷害。", rec: ["zagreus", "nemesis"] },
  { id: "stygius-flurry-slash", weapon: "stygius", name: "Flurry Slash", nameZh: "急速砍殺", effectZh: "長按攻擊可連續揮斬，每下 25 傷害。", rec: ["zagreus", "nemesis"], moves: { attack: { nameZh: "急速砍殺", damage: "25" } } },
  { id: "stygius-dash-nova", weapon: "stygius", name: "Dash Nova", nameZh: "劍陣四方", effectZh: "特殊改為向前衝鋒，並獲得 0.8 秒堅韌（Sturdy）。", rec: ["arthur", "zagreus"], moves: { special: { nameZh: "劍陣四方", damage: "50", noteZh: "衝鋒並獲得堅韌" } } },
  { id: "stygius-world-splitter", weapon: "stygius", name: "World Splitter", nameZh: "力劈天下", effectZh: "攻擊改為單次重斬，基礎傷害 90。", rec: ["arthur"], moves: { attack: { nameZh: "力劈天下", damage: "90" } } },
  { id: "stygius-double-nova", weapon: "stygius", name: "Double Nova", nameZh: "雙重新星", effectZh: "特殊攻擊爆發兩次。", rec: ["poseidon"], moves: { special: { nameZh: "雙重新星", damage: "50 × 2" } } },

  { id: "varatha-extending-jab", weapon: "varatha", name: "Extending Jab", nameZh: "延展突刺", effectZh: "攻擊射程更長。", rec: ["zagreus", "hades"] },
  { id: "varatha-flaring-spin", weapon: "varatha", name: "Flaring Spin", nameZh: "熾熱迴旋", effectZh: "迴旋斬範圍與傷害提高。", rec: ["hades"] },
  { id: "varatha-exploding-launcher", weapon: "varatha", name: "Exploding Launcher", nameZh: "爆破投擲", effectZh: "擲槍命中時爆炸。", rec: ["achilles"] },
  { id: "varatha-charged-skewer", weapon: "varatha", name: "Charged Skewer", nameZh: "蓄力穿刺", effectZh: "可蓄力擲槍，傷害更高。", rec: ["achilles"] },
  { id: "varatha-quick-spin", weapon: "varatha", name: "Quick Spin", nameZh: "迅速迴旋", effectZh: "迴旋斬蓄力更快。", rec: ["guan-yu", "hades"] },

  { id: "aegis-dashing-wallop", weapon: "aegis", name: "Dashing Wallop", nameZh: "衝刺猛擊", effectZh: "衝刺攻擊改為範圍猛擊。", rec: ["zagreus", "chaos"] },
  { id: "aegis-sudden-rush", weapon: "aegis", name: "Sudden Rush", nameZh: "驟然衝鋒", effectZh: "公牛衝鋒蓄力更快。", rec: ["zagreus", "beowulf"] },
  { id: "aegis-dread-flight", weapon: "aegis", name: "Dread Flight", nameZh: "恐懼飛行", effectZh: "擲盾彈跳更多次。", rec: ["chaos"] },
  { id: "aegis-charged-shot", weapon: "aegis", name: "Charged Shot", nameZh: "蓄力射擊", effectZh: "長按特殊發射砲擊。", rec: ["zeus"], moves: { special: { nameZh: "蓄力砲擊", damage: "50", noteZh: "長按特殊發射" } } },
  { id: "aegis-empowering-flight", weapon: "aegis", name: "Empowering Flight", nameZh: "強化飛行", effectZh: "擲盾後攻擊與特殊更強。", rec: ["zeus", "chaos"] },

  { id: "coronacht-triple-shot", weapon: "coronacht", name: "Triple Shot", nameZh: "三連射", effectZh: "攻擊同時射出三箭。", rec: ["zagreus", "hera"], moves: { attack: { nameZh: "三連射", damage: "20 × 3" } } },
  { id: "coronacht-flurry-shot", weapon: "coronacht", name: "Flurry Shot", nameZh: "連射", effectZh: "攻擊更快，完美蓄力窗口更寬。", rec: ["zagreus", "chiron"] },
  { id: "coronacht-sniper-shot", weapon: "coronacht", name: "Sniper Shot", nameZh: "狙擊射擊", effectZh: "完美蓄力傷害大幅提高。", rec: ["zagreus", "rama"], moves: { attack: { nameZh: "狙擊射擊", damage: "20", noteZh: "完美蓄力大增" } } },
  { id: "coronacht-charged-volley", weapon: "coronacht", name: "Charged Volley", nameZh: "蓄力齊射", effectZh: "可蓄力特殊，射出更多箭。", rec: ["chiron"] },
  { id: "coronacht-concentrated-volley", weapon: "coronacht", name: "Concentrated Volley", nameZh: "集中齊射", effectZh: "特殊箭更集中、更痛。", rec: ["chiron", "rama"] },

  { id: "malphon-long-knuckle", weapon: "malphon", name: "Long Knuckle", nameZh: "長拳", effectZh: "攻擊射程更長。", rec: ["zagreus", "demeter"] },
  { id: "malphon-rolling-knuckle", weapon: "malphon", name: "Rolling Knuckle", nameZh: "滾動拳", effectZh: "衝刺攻擊改為範圍拳擊。", rec: ["zagreus", "gilgamesh"] },
  { id: "malphon-kinetic-launcher", weapon: "malphon", name: "Kinetic Launcher", nameZh: "動能發射", effectZh: "特殊把敵人打飛。", rec: ["talos"], moves: { special: { nameZh: "動能發射", damage: "30", noteZh: "把敵人打飛" } } },
  { id: "malphon-draining-cutter", weapon: "malphon", name: "Draining Cutter", nameZh: "汲取切割", effectZh: "特殊命中回復生命。", rec: ["demeter", "gilgamesh"] },
  { id: "malphon-rending-claws", weapon: "malphon", name: "Rending Claws", nameZh: "撕裂之爪", effectZh: "重創持續更久。", rec: ["gilgamesh"] },

  { id: "exagryph-cluster-bomb", weapon: "exagryph", name: "Cluster Bomb", nameZh: "集束炸彈", effectZh: "特殊分裂成多枚榴彈。", rec: ["eris", "zagreus"] },
  { id: "exagryph-hazard-bomb", weapon: "exagryph", name: "Hazard Bomb", nameZh: "危險炸彈", effectZh: "榴彈落地後延遲爆炸、範圍更大。", rec: ["eris"] },
  { id: "exagryph-targeting-system", weapon: "exagryph", name: "Targeting System", nameZh: "鎖定系統", effectZh: "攻擊自動追蹤。", rec: ["zagreus", "hestia"] },
  { id: "exagryph-delta-chamber", weapon: "exagryph", name: "Delta Chamber", nameZh: "三角彈巢", effectZh: "攻擊三連發且無需裝填。", rec: ["zagreus"], moves: { attack: { nameZh: "三連發", damage: "10 × 3", noteZh: "無需裝填" } } },
  { id: "exagryph-eternal-chamber", weapon: "exagryph", name: "Eternal Chamber", nameZh: "永恆彈巢", effectZh: "裝填更快。", rec: ["hestia", "lucifer"] },
  { id: "exagryph-seeking-fire", weapon: "exagryph", name: "Seeking Fire", nameZh: "追蹤射擊", effectZh: "光束會轉向敵人。", rec: ["lucifer"], moves: { attack: { nameZh: "追蹤光束", damage: "持續" } } },
];
